"""reset_db_to_uuid

Revision ID: a2399be682fb
Revises: 
Create Date: 2026-01-26 17:51:37.247550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2399be682fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('new_words_this_week', sa.Integer(), nullable=True),
    sa.Column('practice_sessions_this_week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('front_template', sa.Text(), nullable=False),
    sa.Column('back_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_templates_user_id'), 'card_templates', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('words_per_week', sa.Integer(), nullable=True),
    sa.Column('practice_sessions_per_week', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_language'), 'practice_sessions', ['language'], unique=False)
    op.create_index(op.f('ix_practice_sessions_timestamp'), 'practice_sessions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    op.create_table('reading_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('difficulty_score', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_content_language'), 'reading_content', ['language'], unique=False)
    op.create_index(op.f('ix_reading_content_user_id'), 'reading_content', ['user_id'], unique=False)
    op.create_table('video_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('target_language', sa.String(length=50), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammar_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_content_created_at'), 'video_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_content_target_language'), 'video_content', ['target_language'], unique=False)
    op.create_index(op.f('ix_video_content_user_id'), 'video_content', ['user_id'], unique=False)
    op.create_table('writing_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=True),
    sa.Column('grammar_feedback', sa.Text(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_submissions_created_at'), 'writing_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_writing_submissions_language'), 'writing_submissions', ['language'], unique=False)
    op.create_index(op.f('ix_writing_submissions_user_id'), 'writing_submissions', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=10), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('default_template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_template_id'], ['card_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_language'), 'decks', ['language'], unique=False)
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    op.create_table('grammar_exercise_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reading_content_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('total_exercises', sa.Integer(), nullable=True),
    sa.Column('completed_exercises', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reading_content_id'], ['reading_content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_exercise_sets_created_at'), 'grammar_exercise_sets', ['created_at'], unique=False)
    op.create_index(op.f('ix_grammar_exercise_sets_language'), 'grammar_exercise_sets', ['language'], unique=False)
    op.create_index(op.f('ix_grammar_exercise_sets_user_id'), 'grammar_exercise_sets', ['user_id'], unique=False)
    op.create_table('video_exercise_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_exercise_attempts_attempted_at'), 'video_exercise_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_video_exercise_attempts_user_id'), 'video_exercise_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_exercise_attempts_video_id'), 'video_exercise_attempts', ['video_id'], unique=False)
    op.create_table('grammar_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_set_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('grammar_point', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('correct_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempted', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_set_id'], ['grammar_exercise_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_exercises_exercise_set_id'), 'grammar_exercises', ['exercise_set_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('grammatical_breakdown', sa.Text(), nullable=True),
    sa.Column('literal_translation', sa.String(length=200), nullable=True),
    sa.Column('reading_content_id', sa.UUID(), nullable=True),
    sa.Column('encounters', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('familiarity_score', sa.Integer(), nullable=True),
    sa.Column('easiness_factor', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_content_id'], ['reading_content.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'term', name='uq_deck_term')
    )
    op.create_index(op.f('ix_words_deck_id'), 'words', ['deck_id'], unique=False)
    op.create_index(op.f('ix_words_next_review_date'), 'words', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_words_status'), 'words', ['status'], unique=False)
    op.create_index(op.f('ix_words_term'), 'words', ['term'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('word_id', sa.UUID(), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=True),
    sa.Column('easiness_factor', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['card_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cards_next_review_date'), 'cards', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_cards_word_id'), 'cards', ['word_id'], unique=False)
    op.create_table('grammar_exercise_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['grammar_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_exercise_attempts_created_at'), 'grammar_exercise_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_grammar_exercise_attempts_exercise_id'), 'grammar_exercise_attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_grammar_exercise_attempts_user_id'), 'grammar_exercise_attempts', ['user_id'], unique=False)
    op.create_table('video_vocabulary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.String(length=10), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_vocabulary_video_id'), 'video_vocabulary', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_vocabulary_word_id'), 'video_vocabulary', ['word_id'], unique=False)
    op.create_table('word_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('reading_content_id', sa.UUID(), nullable=True),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reading_content_id'], ['reading_content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_contexts_word_id'), 'word_contexts', ['word_id'], unique=False)
    op.create_table('practice_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_reviews_card_id'), 'practice_reviews', ['card_id'], unique=False)
    op.create_index(op.f('ix_practice_reviews_session_id'), 'practice_reviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_practice_reviews_timestamp'), 'practice_reviews', ['timestamp'], unique=False)
    op.create_index(op.f('ix_practice_reviews_user_id'), 'practice_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_reviews_user_id'), table_name='practice_reviews')
    op.drop_index(op.f('ix_practice_reviews_timestamp'), table_name='practice_reviews')
    op.drop_index(op.f('ix_practice_reviews_session_id'), table_name='practice_reviews')
    op.drop_index(op.f('ix_practice_reviews_card_id'), table_name='practice_reviews')
    op.drop_table('practice_reviews')
    op.drop_index(op.f('ix_word_contexts_word_id'), table_name='word_contexts')
    op.drop_table('word_contexts')
    op.drop_index(op.f('ix_video_vocabulary_word_id'), table_name='video_vocabulary')
    op.drop_index(op.f('ix_video_vocabulary_video_id'), table_name='video_vocabulary')
    op.drop_table('video_vocabulary')
    op.drop_index(op.f('ix_grammar_exercise_attempts_user_id'), table_name='grammar_exercise_attempts')
    op.drop_index(op.f('ix_grammar_exercise_attempts_exercise_id'), table_name='grammar_exercise_attempts')
    op.drop_index(op.f('ix_grammar_exercise_attempts_created_at'), table_name='grammar_exercise_attempts')
    op.drop_table('grammar_exercise_attempts')
    op.drop_index(op.f('ix_cards_word_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_next_review_date'), table_name='cards')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_words_term'), table_name='words')
    op.drop_index(op.f('ix_words_status'), table_name='words')
    op.drop_index(op.f('ix_words_next_review_date'), table_name='words')
    op.drop_index(op.f('ix_words_deck_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_grammar_exercises_exercise_set_id'), table_name='grammar_exercises')
    op.drop_table('grammar_exercises')
    op.drop_index(op.f('ix_video_exercise_attempts_video_id'), table_name='video_exercise_attempts')
    op.drop_index(op.f('ix_video_exercise_attempts_user_id'), table_name='video_exercise_attempts')
    op.drop_index(op.f('ix_video_exercise_attempts_attempted_at'), table_name='video_exercise_attempts')
    op.drop_table('video_exercise_attempts')
    op.drop_index(op.f('ix_grammar_exercise_sets_user_id'), table_name='grammar_exercise_sets')
    op.drop_index(op.f('ix_grammar_exercise_sets_language'), table_name='grammar_exercise_sets')
    op.drop_index(op.f('ix_grammar_exercise_sets_created_at'), table_name='grammar_exercise_sets')
    op.drop_table('grammar_exercise_sets')
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_language'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_writing_submissions_user_id'), table_name='writing_submissions')
    op.drop_index(op.f('ix_writing_submissions_language'), table_name='writing_submissions')
    op.drop_index(op.f('ix_writing_submissions_created_at'), table_name='writing_submissions')
    op.drop_table('writing_submissions')
    op.drop_index(op.f('ix_video_content_user_id'), table_name='video_content')
    op.drop_index(op.f('ix_video_content_target_language'), table_name='video_content')
    op.drop_index(op.f('ix_video_content_created_at'), table_name='video_content')
    op.drop_table('video_content')
    op.drop_index(op.f('ix_reading_content_user_id'), table_name='reading_content')
    op.drop_index(op.f('ix_reading_content_language'), table_name='reading_content')
    op.drop_table('reading_content')
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_timestamp'), table_name='practice_sessions')
    op.drop_index(op.f('ix_practice_sessions_language'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    op.drop_table('goals')
    op.drop_index(op.f('ix_card_templates_user_id'), table_name='card_templates')
    op.drop_table('card_templates')
    op.drop_table('users')
    # ### end Alembic commands ###
