"""added flashcard templates

Revision ID: b01f8f6d20ed
Revises: 386fa10b6027
Create Date: 2026-01-23 15:26:21.352053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01f8f6d20ed'
down_revision: Union[str, None] = '386fa10b6027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('default_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'decks', 'card_templates', ['default_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.drop_column('decks', 'default_template_id')
    # ### end Alembic commands ###
