"""updating for user auth

Revision ID: e74342a5cf4a
Revises: 3dfb7cb90b17
Create Date: 2026-01-22 13:11:15.159106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74342a5cf4a'
down_revision: Union[str, None] = '3dfb7cb90b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=True),
    sa.Column('grammar_feedback', sa.Text(), nullable=True),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_content_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('total_exercises', sa.Integer(), nullable=True),
    sa.Column('completed_exercises', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reading_content_id'], ['reading_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_set_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('grammar_point', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('correct_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempted', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_set_id'], ['grammar_exercise_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_exercise_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['grammar_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cards', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_cards_word_id', 'cards', 'words', ['word_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_constraint('fk_cards_word_id', 'cards', type_='foreignkey')
    op.drop_column('cards', 'word_id')
    op.drop_table('grammar_exercise_attempts')
    op.drop_table('grammar_exercises')
    op.drop_table('grammar_exercise_sets')
    op.drop_table('writing_submissions')
    # ### end Alembic commands ###
